service: notification-service

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - Fn::GetAtt:
            - NotificationsQueue
            - Arn
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  notificationLambda:
    handler: dist/infrastructure/entrypoints/lambda.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotificationsQueue
              - Arn

resources:
  Resources:
    NotificationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: notifications-queue


package:
  individually: true
  patterns:
    - '!test/**'
    - '!src/**'
    - '!coverage/**'
    - '!*.md'
    - '!tsconfig.json'
    - '!jest.config.js'